#!/usr/bin/env python3
import argparse
from pathlib import Path
from control_runtime import validate_target_project_root

MARKER = "<!-- generated-by: engineering-assistant -->"

def build_content(project_name: str) -> str:
    return f'''# AGENTS.md
{MARKER}

## Repository Goal
- Maintain {project_name} through the engineering-assistant control plane.
- Treat `artifacts/_control/task-context.agent.md` as the task entrypoint before broad document search.

## Required Entry Checks
- Read `artifacts/_control/current-task.json`, `task-context.agent.md`, `implementation-contract.json`, and `quality-contract.json`.
- Read the task rule pack under `artifacts/rule-governance/task-rule-packs/` and cite rule ids in implementation, self-test, quality, and review evidence.
- Run `python3 engineering-assistant/scripts/run_controlled_task.py --root . --mode audit-readonly` before review-only work.

## Scope And Safety
- Do not expand scope outside `implementation-contract.json`.
- Stop on stale control-plane evidence, blocking open questions, missing approvals, production actions, or failed quality gates.
- Do not replace failed gates with prose explanations; fix, block, or ask for human review.
'''

def main():
    parser = argparse.ArgumentParser(description="Create a short target-project AGENTS.md entrypoint for the control plane.")
    parser.add_argument("--root", required=True)
    parser.add_argument("--project-name", default="this repository")
    parser.add_argument("--output", default="AGENTS.md")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    root = validate_target_project_root(Path(args.root))
    output = root / args.output
    content = build_content(args.project_name)
    if args.dry_run:
        print(content)
        return
    if output.exists() and MARKER not in output.read_text(encoding="utf-8") and not args.force:
        raise SystemExit(f"{args.output} exists and is not generated by engineering-assistant; rerun with --force after human review")
    output.write_text(content, encoding="utf-8")
    print(output)

if __name__ == "__main__":
    main()
